---
apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    buildUrl: "http://jenkins.jenkins.svc.cluster.local/job/Samples-VaultIntegration/job/vault-integration-test/1/"
    runUrl: "job/Samples-VaultIntegration/job/vault-integration-test/1/"
  labels:
    jenkins/kube-default: "true"
    app: "jenkins"
    component: "agent"
    jenkins/jenkins-jenkins-agent: "true"
    jenkins/label-digest: "a96bc6352cb0632aa3ce7c32a6b12c4a3b8ef7ba"
    jenkins/label: "Samples-VaultIntegration_vault-integration-test_1-g4nxh"
  name: "samples-vaultintegration-vault-integration-test-1-g4nxh-l-291wd"
  namespace: "jenkins"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "jk_role"
            operator: "In"
            values:
            - "slave"
  containers:
  - args:
    - "99d"
    command:
    - "sleep"
    image: "gcr.io/devops-practice-277006/cd-jk-upgrade/cd-jenkins-agent:2.0"
    name: "custom-jnlp"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - args:
    - "99d"
    command:
    - "sleep"
    image: "ubuntu"
    name: "shell"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - args:
    - "99d"
    command:
    - "sleep"
    env:
    - name: "GOOGLE_APPLICATION_CREDENTIALS"
      value: "/secret/jenkins-sa-devops-practice.json"
    image: "gcr.io/kaniko-project/executor:debug-539ddefcae3fd6b411a95982a830d987f4214251"
    imagePullPolicy: "Always"
    name: "kaniko"
    volumeMounts:
    - mountPath: "/secret"
      name: "kaniko-secret"
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_AGENT_NAME"
      value: "samples-vaultintegration-vault-integration-test-1-g4nxh-l-291wd"
    - name: "JENKINS_WEB_SOCKET"
      value: "true"
    - name: "JENKINS_NAME"
      value: "samples-vaultintegration-vault-integration-test-1-g4nxh-l-291wd"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "JENKINS_URL"
      value: "http://jenkins.jenkins.svc.cluster.local/"
    image: "jenkins/inbound-agent:4.11-1-jdk11"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "256Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  nodeSelector:
    jk_role: "slave"
  restartPolicy: "Never"
  serviceAccountName: "cd-jenkins"
  tolerations:
  - effect: "NoSchedule"
    key: "jk_role"
    operator: "Equal"
    value: "slave"
  volumes:
  - name: "kaniko-secret"
    secret:
      secretName: "kaniko-secret"
  - emptyDir:
      medium: ""
    name: "workspace-volume"
